<template>
    <div class="grid">
        <div class="col-12">
            <div class="card">
                <div class="flex justify-content-between align-items-center mb-4">
                    <h5 class="m-0">Monitoring Reports</h5>
                    <div class="flex gap-2">
                        <Button icon="pi pi-plus" 
                                label="Generate Report" 
                                @click="showGenerateDialog = true" />
                        <Button icon="pi pi-refresh" 
                                label="Refresh" 
                                @click="loadReports" 
                                :loading="loading" 
                                class="p-button-outlined" />
                    </div>
                </div>

                <!-- Report Filters -->
                <div class="flex flex-wrap gap-3 mb-4">
                    <Dropdown v-model="selectedReportType" 
                              :options="reportTypes" 
                              optionLabel="label" 
                              optionValue="value"
                              placeholder="All Report Types" 
                              class="w-12rem" 
                              showClear />
                    <Dropdown v-model="selectedPeriod" 
                              :options="periodOptions" 
                              optionLabel="label" 
                              optionValue="value"
                              placeholder="All Periods" 
                              class="w-12rem" 
                              showClear />
                    <Calendar v-model="dateRange" 
                              selectionMode="range" 
                              :manualInput="false"
                              placeholder="Date Range" 
                              class="w-15rem" />
                </div>

                <!-- Reports Table -->
                <DataTable :value="filteredReports" 
                           :paginator="true" 
                           :rows="10"
                           :loading="loading"
                           responsiveLayout="scroll"
                           :sortField="'generatedAt'" 
                           :sortOrder="-1">
                    
                    <Column field="title" header="Report Title" :sortable="true">
                        <template #body="slotProps">
                            <div>
                                <div class="font-medium">{{ slotProps.data.title }}</div>
                                <div class="text-500 text-sm">{{ slotProps.data.description }}</div>
                            </div>
                        </template>
                    </Column>
                    
                    <Column field="type" header="Type" :sortable="true" style="width: 10rem">
                        <template #body="slotProps">
                            <Tag :value="slotProps.data.type" 
                                 :severity="getReportTypeColor(slotProps.data.type)" />
                        </template>
                    </Column>
                    
                    <Column field="period" header="Period" :sortable="true" style="width: 8rem">
                        <template #body="slotProps">
                            {{ slotProps.data.period }}
                        </template>
                    </Column>
                    
                    <Column field="generatedAt" header="Generated" :sortable="true" style="width: 12rem">
                        <template #body="slotProps">
                            <div>
                                <div>{{ formatDate(slotProps.data.generatedAt) }}</div>
                                <div class="text-500 text-sm">{{ formatTime(slotProps.data.generatedAt) }}</div>
                            </div>
                        </template>
                    </Column>
                    
                    <Column field="generatedBy" header="Generated By" style="width: 10rem">
                        <template #body="slotProps">
                            <div class="flex align-items-center">
                                <Avatar :label="slotProps.data.generatedBy.charAt(0)" 
                                        size="small" 
                                        class="mr-2" />
                                {{ slotProps.data.generatedBy }}
                            </div>
                        </template>
                    </Column>
                    
                    <Column field="status" header="Status" :sortable="true" style="width: 8rem">
                        <template #body="slotProps">
                            <Tag :value="slotProps.data.status" 
                                 :severity="getStatusColor(slotProps.data.status)" />
                        </template>
                    </Column>
                    
                    <Column header="Actions" style="width: 12rem">
                        <template #body="slotProps">
                            <div class="flex gap-1">
                                <Button icon="pi pi-eye" 
                                        class="p-button-rounded p-button-text p-button-sm" 
                                        @click="viewReport(slotProps.data)"
                                        v-tooltip.top="'View Report'" />
                                <Button icon="pi pi-download" 
                                        class="p-button-rounded p-button-text p-button-sm" 
                                        @click="downloadReport(slotProps.data)"
                                        v-tooltip.top="'Download'"
                                        :disabled="slotProps.data.status !== 'completed'" />
                                <Button icon="pi pi-share-alt" 
                                        class="p-button-rounded p-button-text p-button-sm" 
                                        @click="shareReport(slotProps.data)"
                                        v-tooltip.top="'Share'"
                                        :disabled="slotProps.data.status !== 'completed'" />
                                <Button icon="pi pi-trash" 
                                        class="p-button-rounded p-button-text p-button-sm p-button-danger" 
                                        @click="deleteReport(slotProps.data)"
                                        v-tooltip.top="'Delete'" />
                            </div>
                        </template>
                    </Column>
                </DataTable>
            </div>
        </div>

        <!-- Generate Report Dialog -->
        <Dialog v-model:visible="showGenerateDialog" 
                header="Generate New Report" 
                :modal="true" 
                :style="{ width: '40vw' }"
                :breakpoints="{ '960px': '75vw', '641px': '90vw' }">
            <div class="grid">
                <div class="col-12">
                    <div class="field">
                        <label for="reportTitle">Report Title *</label>
                        <InputText id="reportTitle" 
                                   v-model="newReport.title" 
                                   class="w-full mt-2" 
                                   placeholder="Enter report title" />
                    </div>
                </div>
                <div class="col-12">
                    <div class="field">
                        <label for="reportType">Report Type *</label>
                        <Dropdown id="reportType" 
                                  v-model="newReport.type" 
                                  :options="reportTypes" 
                                  optionLabel="label" 
                                  optionValue="value"
                                  placeholder="Select report type" 
                                  class="w-full mt-2" />
                    </div>
                </div>
                <div class="col-12 md:col-6">
                    <div class="field">
                        <label for="reportPeriod">Period *</label>
                        <Dropdown id="reportPeriod" 
                                  v-model="newReport.period" 
                                  :options="periodOptions" 
                                  optionLabel="label" 
                                  optionValue="value"
                                  placeholder="Select period" 
                                  class="w-full mt-2" />
                    </div>
                </div>
                <div class="col-12 md:col-6">
                    <div class="field">
                        <label for="reportFormat">Format</label>
                        <Dropdown id="reportFormat" 
                                  v-model="newReport.format" 
                                  :options="formatOptions" 
                                  optionLabel="label" 
                                  optionValue="value"
                                  placeholder="Select format" 
                                  class="w-full mt-2" />
                    </div>
                </div>
                <div class="col-12" v-if="newReport.period === 'custom'">
                    <div class="field">
                        <label for="customDateRange">Custom Date Range *</label>
                        <Calendar id="customDateRange" 
                                  v-model="newReport.dateRange" 
                                  selectionMode="range" 
                                  :manualInput="false"
                                  placeholder="Select date range" 
                                  class="w-full mt-2" />
                    </div>
                </div>
                <div class="col-12">
                    <div class="field">
                        <label for="reportDescription">Description</label>
                        <Textarea id="reportDescription" 
                                  v-model="newReport.description" 
                                  rows="3" 
                                  class="w-full mt-2" 
                                  placeholder="Optional description..." />
                    </div>
                </div>
                <div class="col-12">
                    <div class="field">
                        <label>Include Sections</label>
                        <div class="mt-2">
                            <div class="flex flex-wrap gap-3">
                                <div class="flex align-items-center">
                                    <Checkbox id="includeTransactions" 
                                              v-model="newReport.sections" 
                                              value="transactions" />
                                    <label for="includeTransactions" class="ml-2">Transaction Analysis</label>
                                </div>
                                <div class="flex align-items-center">
                                    <Checkbox id="includeAlerts" 
                                              v-model="newReport.sections" 
                                              value="alerts" />
                                    <label for="includeAlerts" class="ml-2">Alert Summary</label>
                                </div>
                                <div class="flex align-items-center">
                                    <Checkbox id="includeRisk" 
                                              v-model="newReport.sections" 
                                              value="risk" />
                                    <label for="includeRisk" class="ml-2">Risk Assessment</label>
                                </div>
                                <div class="flex align-items-center">
                                    <Checkbox id="includeCompliance" 
                                              v-model="newReport.sections" 
                                              value="compliance" />
                                    <label for="includeCompliance" class="ml-2">Compliance Status</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <template #footer>
                <Button label="Cancel" 
                        icon="pi pi-times" 
                        @click="showGenerateDialog = false" 
                        class="p-button-text" />
                <Button label="Generate Report" 
                        icon="pi pi-check" 
                        @click="generateReport" 
                        :disabled="!isReportValid" />
            </template>
        </Dialog>

        <!-- Report Viewer Dialog -->
        <Dialog v-model:visible="showReportDialog" 
                :header="selectedReport?.title" 
                :modal="true" 
                :style="{ width: '80vw' }"
                :breakpoints="{ '960px': '90vw', '641px': '95vw' }"
                maximizable>
            <div v-if="selectedReport" class="report-viewer">
                <!-- Report Header -->
                <div class="flex justify-content-between align-items-start mb-4">
                    <div>
                        <h6 class="m-0 mb-2">{{ selectedReport.title }}</h6>
                        <p class="text-500 m-0">{{ selectedReport.description }}</p>
                        <div class="flex gap-2 mt-2">
                            <Tag :value="selectedReport.type" 
                                 :severity="getReportTypeColor(selectedReport.type)" />
                            <Tag :value="selectedReport.period" severity="info" />
                            <Tag :value="selectedReport.status" 
                                 :severity="getStatusColor(selectedReport.status)" />
                        </div>
                    </div>
                    <div class="text-right">
                        <div class="text-sm text-500">Generated: {{ formatDateTime(selectedReport.generatedAt) }}</div>
                        <div class="text-sm text-500">By: {{ selectedReport.generatedBy }}</div>
                    </div>
                </div>

                <!-- Report Content -->
                <div v-if="selectedReport.status === 'completed'" class="report-content">
                    <!-- Executive Summary -->
                    <div class="mb-4">
                        <h6>Executive Summary</h6>
                        <div class="grid">
                            <div class="col-12 md:col-3">
                                <div class="surface-card p-3 border-round text-center">
                                    <div class="text-2xl font-bold text-blue-500">{{ selectedReport.data?.totalTransactions || 0 }}</div>
                                    <div class="text-500">Total Transactions</div>
                                </div>
                            </div>
                            <div class="col-12 md:col-3">
                                <div class="surface-card p-3 border-round text-center">
                                    <div class="text-2xl font-bold text-orange-500">{{ selectedReport.data?.suspiciousTransactions || 0 }}</div>
                                    <div class="text-500">Suspicious</div>
                                </div>
                            </div>
                            <div class="col-12 md:col-3">
                                <div class="surface-card p-3 border-round text-center">
                                    <div class="text-2xl font-bold text-red-500">{{ selectedReport.data?.alertsGenerated || 0 }}</div>
                                    <div class="text-500">Alerts Generated</div>
                                </div>
                            </div>
                            <div class="col-12 md:col-3">
                                <div class="surface-card p-3 border-round text-center">
                                    <div class="text-2xl font-bold text-green-500">{{ selectedReport.data?.complianceScore || 0 }}%</div>
                                    <div class="text-500">Compliance Score</div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Charts Section -->
                    <div class="mb-4" v-if="selectedReport.data?.charts">
                        <h6>Analytics</h6>
                        <div class="grid">
                            <div class="col-12 md:col-6">
                                <div class="surface-card p-3 border-round">
                                    <h6 class="mb-3">Risk Distribution</h6>
                                    <Chart type="doughnut" 
                                           :data="riskChartData" 
                                           :options="chartOptions" 
                                           class="w-full md:w-30rem" />
                                </div>
                            </div>
                            <div class="col-12 md:col-6">
                                <div class="surface-card p-3 border-round">
                                    <h6 class="mb-3">Transaction Volume Trend</h6>
                                    <Chart type="line" 
                                           :data="volumeChartData" 
                                           :options="chartOptions" 
                                           class="w-full md:w-30rem" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Key Findings -->
                    <div class="mb-4" v-if="selectedReport.data?.findings">
                        <h6>Key Findings</h6>
                        <div class="surface-card p-3 border-round">
                            <ul class="list-none p-0 m-0">
                                <li v-for="finding in selectedReport.data.findings" 
                                    :key="finding.id" 
                                    class="flex align-items-start py-2">
                                    <i :class="getFindingIcon(finding.severity)" 
                                       :style="{ color: getFindingColor(finding.severity) }" 
                                       class="mr-2 mt-1"></i>
                                    <div>
                                        <div class="font-medium">{{ finding.title }}</div>
                                        <div class="text-500 text-sm">{{ finding.description }}</div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <!-- Recommendations -->
                    <div class="mb-4" v-if="selectedReport.data?.recommendations">
                        <h6>Recommendations</h6>
                        <div class="surface-card p-3 border-round">
                            <div v-for="rec in selectedReport.data.recommendations" 
                                 :key="rec.id" 
                                 class="mb-3 last:mb-0">
                                <div class="flex align-items-start">
                                    <Tag :value="rec.priority" 
                                         :severity="getPriorityColor(rec.priority)" 
                                         class="mr-2" />
                                    <div>
                                        <div class="font-medium">{{ rec.title }}</div>
                                        <div class="text-500 text-sm">{{ rec.description }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Loading State -->
                <div v-else-if="selectedReport.status === 'generating'" class="text-center py-4">
                    <ProgressSpinner />
                    <div class="mt-3">Generating report...</div>
                </div>

                <!-- Error State -->
                <div v-else-if="selectedReport.status === 'failed'" class="text-center py-4">
                    <i class="pi pi-exclamation-triangle text-red-500 text-4xl"></i>
                    <div class="mt-3 text-red-500">Report generation failed</div>
                </div>
            </div>
        </Dialog>

        <!-- Share Report Dialog -->
        <Dialog v-model:visible="showShareDialog" 
                header="Share Report" 
                :modal="true" 
                :style="{ width: '30vw' }">
            <div class="field">
                <label for="shareEmails">Email Recipients</label>
                <Chips id="shareEmails" 
                       v-model="shareEmails" 
                       class="w-full mt-2"
                       placeholder="Enter email addresses" />
            </div>
            <div class="field">
                <label for="shareMessage">Message (Optional)</label>
                <Textarea id="shareMessage" 
                          v-model="shareMessage" 
                          rows="3" 
                          class="w-full mt-2" 
                          placeholder="Add a message..." />
            </div>
            <div class="field">
                <div class="flex align-items-center">
                    <Checkbox id="includeRawData" v-model="includeRawData" />
                    <label for="includeRawData" class="ml-2">Include raw data</label>
                </div>
            </div>
            <template #footer>
                <Button label="Cancel" 
                        icon="pi pi-times" 
                        @click="showShareDialog = false" 
                        class="p-button-text" />
                <Button label="Share Report" 
                        icon="pi pi-send" 
                        @click="confirmShare" 
                        :disabled="!shareEmails.length" />
            </template>
        </Dialog>
    </div>
</template>

<script setup>
import Avatar from 'primevue/avatar';
import Button from 'primevue/button';
import Calendar from 'primevue/calendar';
import Chart from 'primevue/chart';
import Checkbox from 'primevue/checkbox';
import Chips from 'primevue/chips';
import Column from 'primevue/column';
import DataTable from 'primevue/datatable';
import Dialog from 'primevue/dialog';
import Dropdown from 'primevue/dropdown';
import InputText from 'primevue/inputtext';
import ProgressSpinner from 'primevue/progressspinner';
import Tag from 'primevue/tag';
import Textarea from 'primevue/textarea';
import { computed, onMounted, ref } from 'vue';

// Reactive data
const reports = ref([]);
const loading = ref(false);
const selectedReport = ref(null);
const showGenerateDialog = ref(false);
const showReportDialog = ref(false);
const showShareDialog = ref(false);

// Filters
const selectedReportType = ref(null);
const selectedPeriod = ref(null);
const dateRange = ref(null);

// New report form
const newReport = ref({
    title: '',
    type: null,
    period: null,
    format: 'PDF',
    dateRange: null,
    description: '',
    sections: ['transactions', 'alerts']
});

// Share dialog
const shareEmails = ref([]);
const shareMessage = ref('');
const includeRawData = ref(false);

// Options
const reportTypes = [
    { label: 'AML Compliance', value: 'aml' },
    { label: 'Transaction Analysis', value: 'transaction' },
    { label: 'Risk Assessment', value: 'risk' },
    { label: 'Alert Summary', value: 'alert' },
    { label: 'Regulatory', value: 'regulatory' },
    { label: 'Executive Summary', value: 'executive' }
];

const periodOptions = [
    { label: 'Last 24 Hours', value: '24h' },
    { label: 'Last 7 Days', value: '7d' },
    { label: 'Last 30 Days', value: '30d' },
    { label: 'Last Quarter', value: '3m' },
    { label: 'Last Year', value: '1y' },
    { label: 'Custom Range', value: 'custom' }
];

const formatOptions = [
    { label: 'PDF', value: 'PDF' },
    { label: 'Excel', value: 'XLSX' },
    { label: 'CSV', value: 'CSV' },
    { label: 'JSON', value: 'JSON' }
];

// Computed properties
const filteredReports = computed(() => {
    let filtered = reports.value;

    if (selectedReportType.value) {
        filtered = filtered.filter(report => report.type === selectedReportType.value);
    }

    if (selectedPeriod.value) {
        filtered = filtered.filter(report => report.period === selectedPeriod.value);
    }

    if (dateRange.value && dateRange.value[0] && dateRange.value[1]) {
        const startDate = dateRange.value[0];
        const endDate = dateRange.value[1];
        filtered = filtered.filter(report => {
            const reportDate = new Date(report.generatedAt);
            return reportDate >= startDate && reportDate <= endDate;
        });
    }

    return filtered;
});

const isReportValid = computed(() => {
    return newReport.value.title && 
           newReport.value.type && 
           newReport.value.period &&
           (newReport.value.period !== 'custom' || newReport.value.dateRange);
});

const riskChartData = computed(() => {
    if (!selectedReport.value?.data?.riskDistribution) return {};
    
    const data = selectedReport.value.data.riskDistribution;
    return {
        labels: ['Low Risk', 'Medium Risk', 'High Risk', 'Critical Risk'],
        datasets: [{
            data: [data.low, data.medium, data.high, data.critical],
            backgroundColor: ['#10B981', '#F59E0B', '#EF4444', '#DC2626'],
            hoverBackgroundColor: ['#059669', '#D97706', '#DC2626', '#B91C1C']
        }]
    };
});

const volumeChartData = computed(() => {
    if (!selectedReport.value?.data?.volumeTrend) return {};
    
    const trend = selectedReport.value.data.volumeTrend;
    return {
        labels: trend.labels,
        datasets: [{
            label: 'Transaction Volume',
            data: trend.data,
            fill: false,
            borderColor: '#3B82F6',
            tension: 0.4
        }]
    };
});

const chartOptions = ref({
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
        legend: {
            position: 'bottom'
        }
    }
});

// Methods
const loadReports = async () => {
    loading.value = true;
    try {
        // Simulate API call
        await new Promise(resolve => setTimeout(resolve, 1000));
        
        reports.value = [
            {
                id: 1,
                title: 'Monthly AML Compliance Report',
                description: 'Comprehensive analysis of AML compliance for the past month',
                type: 'aml',
                period: '30d',
                format: 'PDF',
                status: 'completed',
                generatedAt: new Date(),
                generatedBy: 'Sarah Johnson',
                data: {
                    totalTransactions: 15420,
                    suspiciousTransactions: 89,
                    alertsGenerated: 23,
                    complianceScore: 94,
                    riskDistribution: { low: 14500, medium: 831, high: 78, critical: 11 },
                    volumeTrend: {
                        labels: ['Week 1', 'Week 2', 'Week 3', 'Week 4'],
                        data: [3200, 4100, 3800, 4320]
                    },
                    findings: [
                        {
                            id: 1,
                            severity: 'high',
                            title: 'Increased suspicious activity',
                            description: '15% increase in flagged transactions compared to previous month'
                        },
                        {
                            id: 2,
                            severity: 'medium',
                            title: 'New risk patterns identified',
                            description: 'Emerging patterns in cross-border transactions require monitoring'
                        }
                    ],
                    recommendations: [
                        {
                            id: 1,
                            priority: 'high',
                            title: 'Enhanced monitoring for high-risk jurisdictions',
                            description: 'Implement additional screening for transactions from identified high-risk countries'
                        },
                        {
                            id: 2,
                            priority: 'medium',
                            title: 'Update transaction thresholds',
                            description: 'Review and adjust current monitoring thresholds based on recent patterns'
                        }
                    ]
                }
            },
            {
                id: 2,
                title: 'Weekly Transaction Analysis',
                description: 'Analysis of transaction patterns and anomalies for the past week',
                type: 'transaction',
                period: '7d',
                format: 'Excel',
                status: 'completed',
                generatedAt: new Date(Date.now() - 86400000),
                generatedBy: 'Mike Chen',
                data: {
                    totalTransactions: 3847,
                    suspiciousTransactions: 12,
                    alertsGenerated: 5,
                    complianceScore: 97
                }
            },
            {
                id: 3,
                title: 'Risk Assessment Report',
                description: 'Comprehensive risk assessment for Q4 2024',
                type: 'risk',
                period: '3m',
                format: 'PDF',
                status: 'generating',
                generatedAt: new Date(Date.now() - 300000),
                generatedBy: 'Lisa Rodriguez'
            },
            {
                id: 4,
                title: 'Alert Summary Report',
                description: 'Summary of all alerts generated in the past 24 hours',
                type: 'alert',
                period: '24h',
                format: 'CSV',
                status: 'failed',
                generatedAt: new Date(Date.now() - 1800000),
                generatedBy: 'John Smith'
            }
        ];
    } catch (error) {
        console.error('Error loading reports:', error);
    } finally {
        loading.value = false;
    }
};

const generateReport = async () => {
    try {
        const reportData = {
            ...newReport.value,
            id: Date.now(),
            status: 'generating',
            generatedAt: new Date(),
            generatedBy: 'Current User' // In real app, get from auth context
        };
        
        reports.value.unshift(reportData);
        showGenerateDialog.value = false;
        
        // Reset form
        newReport.value = {
            title: '',
            type: null,
            period: null,
            format: 'PDF',
            dateRange: null,
            description: '',
            sections: ['transactions', 'alerts']
        };
        
        // Simulate report generation
        setTimeout(() => {
            const report = reports.value.find(r => r.id === reportData.id);
            if (report) {
                report.status = 'completed';
                report.data = generateMockReportData();
            }
        }, 5000);
        
        // In a real app, this would make an API call
        console.log('Report generation started:', reportData);
    } catch (error) {
        console.error('Error generating report:', error);
    }
};

const generateMockReportData = () => {
    return {
        totalTransactions: Math.floor(Math.random() * 10000) + 1000,
        suspiciousTransactions: Math.floor(Math.random() * 100) + 10,
        alertsGenerated: Math.floor(Math.random() * 50) + 5,
        complianceScore: Math.floor(Math.random() * 20) + 80,
        riskDistribution: {
            low: Math.floor(Math.random() * 8000) + 2000,
            medium: Math.floor(Math.random() * 500) + 100,
            high: Math.floor(Math.random() * 100) + 20,
            critical: Math.floor(Math.random() * 20) + 5
        },
        volumeTrend: {
            labels: ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5', 'Day 6', 'Day 7'],
            data: Array.from({ length: 7 }, () => Math.floor(Math.random() * 1000) + 500)
        }
    };
};

const viewReport = (report) => {
    selectedReport.value = report;
    showReportDialog.value = true;
};

const downloadReport = (report) => {
    // Simulate file download
    const fileName = `${report.title.replace(/\s+/g, '_')}.${report.format.toLowerCase()}`;
    console.log('Downloading report:', fileName);
    
    // In a real app, this would trigger actual file download
    // const blob = new Blob([reportData], { type: getMimeType(report.format) });
    // const url = URL.createObjectURL(blob);
    // const a = document.createElement('a');
    // a.href = url;
    // a.download = fileName;
    // a.click();
    // URL.revokeObjectURL(url);
};

const shareReport = (report) => {
    selectedReport.value = report;
    shareEmails.value = [];
    shareMessage.value = '';
    includeRawData.value = false;
    showShareDialog.value = true;
};

const confirmShare = () => {
    console.log('Sharing report:', {
        report: selectedReport.value,
        emails: shareEmails.value,
        message: shareMessage.value,
        includeRawData: includeRawData.value
    });
    
    showShareDialog.value = false;
    
    // In a real app, this would make an API call to send emails
};

const deleteReport = (report) => {
    const index = reports.value.findIndex(r => r.id === report.id);
    if (index > -1) {
        reports.value.splice(index, 1);
    }
    
    // In a real app, this would make an API call
    console.log('Report deleted:', report);
};

// Utility methods
const getReportTypeColor = (type) => {
    switch (type) {
        case 'aml': return 'danger';
        case 'transaction': return 'info';
        case 'risk': return 'warning';
        case 'alert': return 'danger';
        case 'regulatory': return 'secondary';
        case 'executive': return 'success';
        default: return 'secondary';
    }
};

const getStatusColor = (status) => {
    switch (status) {
        case 'completed': return 'success';
        case 'generating': return 'warning';
        case 'failed': return 'danger';
        default: return 'secondary';
    }
};

const getFindingIcon = (severity) => {
    switch (severity) {
        case 'high': return 'pi pi-exclamation-triangle';
        case 'medium': return 'pi pi-info-circle';
        case 'low': return 'pi pi-check-circle';
        default: return 'pi pi-circle';
    }
};

const getFindingColor = (severity) => {
    switch (severity) {
        case 'high': return '#EF4444';
        case 'medium': return '#F59E0B';
        case 'low': return '#10B981';
        default: return '#6B7280';
    }
};

const getPriorityColor = (priority) => {
    switch (priority) {
        case 'high': return 'danger';
        case 'medium': return 'warning';
        case 'low': return 'success';
        default: return 'secondary';
    }
};

const formatDate = (date) => {
    return new Date(date).toLocaleDateString();
};

const formatTime = (date) => {
    return new Date(date).toLocaleTimeString();
};

const formatDateTime = (date) => {
    return new Date(date).toLocaleString();
};

// Lifecycle
onMounted(() => {
    loadReports();
});
</script>

<style scoped>
.report-viewer {
    max-height: 70vh;
    overflow-y: auto;
}

.surface-card {
    background: var(--surface-card);
    border: 1px solid var(--surface-border);
}

.report-content h6 {
    color: var(--text-color);
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid var(--surface-border);
}

.field {
    margin-bottom: 1rem;
}

.field label {
    display: block;
    margin-bottom: 0.5rem;
    font-weight: 500;
    color: var(--text-color);
}

:deep(.p-datatable .p-datatable-tbody > tr > td) {
    padding: 0.75rem;
}

:deep(.p-dialog .p-dialog-content) {
    padding: 1.5rem;
}

:deep(.p-chart) {
    position: relative;
}

.report-viewer::-webkit-scrollbar {
    width: 6px;
}

.report-viewer::-webkit-scrollbar-track {
    background: var(--surface-ground);
}

.report-viewer::-webkit-scrollbar-thumb {
    background: var(--surface-border);
    border-radius: 3px;
}

.report-viewer::-webkit-scrollbar-thumb:hover {
    background: var(--primary-color);
}

@media screen and (max-width: 768px) {
    .report-viewer {
        max-height: 60vh;
    }
    
    :deep(.p-dialog) {
        width: 95vw !important;
        margin: 0 auto;
    }
    
    .flex.gap-1 {
        flex-wrap: wrap;
        gap: 0.25rem;
    }
}
</style>
